### ISSUE TITLE
FizzBuzz improvement

### ISSUE THREAD

**Issue by mstachniuk** [JaroslawMargas/Java-first#1]
https://github.com/JaroslawMargas/Java-first/blob/bd48fc0a7dcb4908c23eec62be00ae7b06e7f937/src/main/java/org/example/lesson07/ForLoop.java#L9

You can do it better. Think for the moment if you need so much if's.

**Comment by JaroslawMargas** [comment]
solutions:
-%15
- creating a String sequence
